---
- name: Install Docker on Ubuntu
  hosts: servers
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"